# Generated by Django 4.0.3 on 2022-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
